name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: Add ability to export maps as PDF
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: Users can't easily share maps outside the application
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you implement this?
      placeholder: Add export button that generates PDF using library X

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      multiple: true
      options:
        - Backend
        - Frontend
        - Domain Layer
        - Application Layer
        - Infrastructure Layer
        - CI/CD
    validations:
      required: true
