name: Feature Implementation
description: Track a planned feature implementation
title: ""
labels: ["enhancement", "planned"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Implementation Tracking
        Create a new feature issue following the project's standard format.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select priority level (use ALL CAPS in issue body)
      options:
        - CRITICAL
        - HIGH
        - MEDIUM
        - LOW
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What's the current implementation status? Use emoji checkboxes (✅ ❌ ⚠️)
      placeholder: |
        - ❌ Feature not implemented
        - ✅ Related feature exists
        - ⚠️ Partially implemented
      value: |
        - ❌
        - ✅
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature, requirements, rationale, or technical approach. Use custom section headers (##) as needed.
      placeholder: |
        ## Rationale
        Why this feature is needed...

        ## Implementation Approach
        Technical details...

        ## Files to Create
        - path/to/file.ts
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Checklist of implementation tasks
      value: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Optional notes, migration info, or references
      placeholder: |
        ---
        *Migrated from: docs/features/planned/feature-name.md*
    validations:
      required: false