name: ♻️ Refactor
description: Technical debt or code improvement
title: "refactor: "
labels: ["refactor", "technical-debt", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for improving the codebase! Please search existing issues before creating a new one.

  - type: checkboxes
    attributes:
      label: Is there an existing issue?
      description: Please search existing issues to avoid duplicates
      options:
        - label: I have searched existing issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Current state
      description: What needs refactoring and why?
      placeholder: TopographyLayer.ts has grown to 1123 lines with 28 methods...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this be refactored?
      placeholder: Split into separate service classes following single responsibility...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this refactor?
      options:
        - low
        - medium
        - high
        - critical
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which area needs refactoring?
      options:
        - backend
        - frontend
        - domain
        - application
        - infrastructure
        - docs
        - ci
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Architecture concerns, breaking changes, migration notes, etc.
      placeholder: |
        Files affected, dependencies, related issues...
