/**
 * Error categories for standardized error handling
 */
export enum ErrorCategory {
  // Core categories
  VALIDATION = 'VALIDATION',
  DOMAIN_RULE = 'DOMAIN_RULE',
  DETERMINISTIC = 'DETERMINISTIC',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  NOT_FOUND = 'NOT_FOUND',
  CONFIGURATION = 'CONFIGURATION',
  EXTERNAL_SERVICE = 'EXTERNAL_SERVICE',

  // Domain context categories
  RELIEF_GENERATION = 'RELIEF_GENERATION',
  NATURAL_FEATURES = 'NATURAL_FEATURES',
  ARTIFICIAL_STRUCTURES = 'ARTIFICIAL_STRUCTURES',
  CULTURAL_ELEMENTS = 'CULTURAL_ELEMENTS',
  MAP_AGGREGATION = 'MAP_AGGREGATION'
}